### ISSUE TITLE
differend hash when registring and authenticating

### ISSUE THREAD

**Issue by giko45** [acoustep/entrust-gui#14]
when a user registers it seems that you HashingModelTrait is used to hash the password when creating users.

authentications uses however the Illuminate\Hashing\BcryptHasher when validating users.

The effect is that no users are authenticated. I assume that i either use the wrong hashing algorithmn when registring (HashingModelTrait is used in "your" User model) or when autheticating.  
 Which hashing algorithmn should be used and what do i need to change to get them the same?

**Comment by giko45** [comment]
commenting away the hashing traits in your User class seemed to solve the issue. How is "your" HashingModelTrait mend to be used with standard hashing?

```
<?php namespace App;

use Esensi\Model\Contracts\HashingModelInterface;
use Esensi\Model\Contracts\ValidatingModelInterface;
**// use Esensi\Model\Traits\HashingModelTrait;**
use Esensi\Model\Traits\ValidatingModelTrait;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, ValidatingModelInterface **#,HashingModelInterface**
{
    use Authenticatable, CanResetPassword, ValidatingModelTrait, EntrustUserTrait;**#, HashingModelTrait;**
```

**Comment by acoustep** [comment]
Hi @giko45 

The Esensi\Model\Traits\ValidatingModelTrait is no longer used due to the issue you've just come across.

Can you see if this comment helps solve your issue? https://github.com/acoustep/entrust-gui/issues/5#issuecomment-221080675

**Comment by acoustep** [comment]
Closing this due to no response, please feel free to reopen if you're still getting an issue.
