### ISSUE TITLE
Duplicate email not handled gracefully

### ISSUE THREAD

**Issue by ethanclevenger91** [acoustep/entrust-gui#15]
Right now if I try to add a user with the same email as a previously entered user, it seems to return null since the email is required to be unique, which ultimately leads to the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `role_user` (`role_id`, `user_id`) values (3, ))
```

Is there something I should be doing on my end to handle duplicate emails or is this a previously unconsidered case? I wager it could redirect back to the form with the same information and an error label of some kind.

**Comment by acoustep** [comment]
Hi @ethanclevenger91 ,

Do you have the the unique validation ruleset added to your User model?

When adding a new user with the same email address, validation should fail and this error should show:

```
The email has already been taken.
```

This should happen before anything is added to the role_user table, which seems to be what's happening in the error that you're getting.

Here's how the User model should look in 5.2 https://github.com/acoustep/entrust-gui/blob/5.2/templates/User.php.txt

**Comment by ethanclevenger91** [comment]
Ah, I was missing `protected $throwValidationExceptions = true;`. I also had to add the code for displaying errors to the forms that come with the library:

```
<div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" placeholder="Email" name="email" value="{{ (Session::has('errors')) ? old('email', '') : $user->email }}">
    {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>
```

I'd be happy to put in a PR and add those if you like.

Thanks so much!

**Comment by acoustep** [comment]
Glad the issue is resolved!

I've just added your changes in. Thank you for your help :)
