### ISSUE TITLE
Encountered the password_confirmation error

### ISSUE THREAD

**Issue by jrubinos** [acoustep/entrust-gui#16]
I encountered a password confirmation error upon editing my user role. While leaving the password fields blank.

But I was able to fix it by updating my UserRepositoryEloquent.php.
I unset the model->password and model->password_confirmation.

**Comment by acoustep** [comment]
Hi @jrubinos,

Are you using the password confirmation feature?

If you aren't, can you make sure that you have `"confirmable" => false,` in your entrust-gui config file?

**Comment by jrubinos** [comment]
Hi acoustep,
  Yes, I am using the password confirmation feature.

**Comment by acoustep** [comment]
Hi @jrubinos 

I've just tested the code from the docs and I'm having no issues, would you be able to provide your User model so I can take a look at what could be causing it?

If you let me know what version of Laravel your using that might help as well.

Thanks

**Comment by acoustep** [comment]
Closing this issue due to lack of response. 

Please feel free to reopen if you are still having this issue.
