### ISSUE TITLE
What are these 'breaking changes'?

### ISSUE THREAD

**Issue by freddyheppell** [acoustep/entrust-gui#2]
I was thinking of using this on a new project I'm making, what is the risk of using it now?

**Comment by acoustep** [comment]
Sorry, I've only just noticed this issue!

I've finished the majority of the features now so there shouldn't be any major changes. What's left is mostly testing and refactoring.

**Comment by acoustep** [comment]
There is one breaking change that now requires updating the User model when upgrading to 0.4.0.

I'm closing this issue for now - please feel free to reopen if you have any more queries!
