### ISSUE TITLE
manyTomany events

### ISSUE THREAD

**Issue by jubayerarefin** [acoustep/entrust-gui#21]
First of all, thanks for providing a nice package for `Entrust`. I would like like to know how can I add/extend the package to add manyTomany events such as: `attached`, `detached` or `synced`.

I have added a function to my `User` and `Role` model and I can listen to the events. But need to use for all the `attach`, `detach` or `sync` done from the package.

Here is my function:

`public function syncRoles($ids, $detaching = true)
    {
        static::$dispatcher->fire(new Syncing($this, $ids, $detaching));

```
    $result = $this->roles()->sync($ids, $detaching);

    if ($detached = $result['detached']) {
        static::$dispatcher->fire(new Detached($this, $detached));
    }

    if ($attached = $result['attached']) {
        static::$dispatcher->fire(new Attached($this, $attached));
    }
}`
```

Any kind of help is appreciated. Thanks in advance.

**Comment by acoustep** [comment]
Hi @jubayerarefin 

I appreciate the kind words, thank you!

This isn't currently possible, however, I can create a new event on UserUpdate which would give you access to the new saved User model and the previous User model - including roles.

You would have an event listener that looked similar to this:

```
//start of listener goes here ...
public function handle(UserSyncRolesEvent $event)
    {
      // Previous state would be available in $event->old_user->roles
      // Newly saved state would be available in $event->user->roles
    }
```

From these two properties, `old_user` and `user`, you would be able to figure out which roles have been added and which have been detached.

Would that be an ok solution for you?

**Comment by jubayerarefin** [comment]
Hi @acoustep thanks for your response. Yes, I guess I can use the solution you have suggested. Though it would be nice to have two properties `attached` & `detached` with the array of added and removed id of the roles.

Thanks again.
