### ISSUE TITLE
Future of entrust-gui

### ISSUE THREAD

**Issue by alex-LE** [acoustep/entrust-gui#22]
Hi, it seems that Zizaco/entrust will no longer be maintained and its still not working with Laravel 5.3.

Are there any plans to migrate to one of the forks?

**Comment by acoustep** [comment]
Hi @alex-LE, It's a shame to hear about Entrust no longer being maintained.

I'll most likely create a new branch for 5.3 with a fork of Entrust. At the moment I'm considering https://github.com/santigarcor/laratrust.

**Comment by ethanclevenger91** [comment]
Seems to be back from the dead shortly after this was opened. Hopefully it sticks.

**Comment by acoustep** [comment]
That's good to hear. Ideally I'd like to keep it on the original repo but I'll keep my eye on the activity.

Closing this issue for now.
