### ISSUE TITLE
Cannot have an empty name

### ISSUE THREAD

**Issue by sudinem** [acoustep/entrust-gui#27]
When I run php artisan vendor:publish --tag="config", I get this error:

The command defined in "Acoustep\EntrustGui\Console\Commands\GenerateModels" cannot have an empty name.

I'm using laravel 5.0. How to resolve this issue ??

**Comment by acoustep** [comment]
Hi @sudinem 

After some investigation I've found that Laravel 5.0 uses a slightly different syntax for commands.

I've created a new branch called 5.0. to use it put this in your composer.json and run ```composer update```

```
"acoustep/entrust-gui": "5.0.x-dev",
```

Let me know how you get on!
