### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by ruelluna** [acoustep/entrust-gui#3]
I need this awesome package but I pulled https://github.com/hiendv/entrust for 5.2 compatibility.

**Comment by acoustep** [comment]
I'll try to get this sorted tonight 😀.

**Comment by acoustep** [comment]
Just to give you an update: It seems that one of the other dependencies (esensi/model) which is used for validation and password hashing does not yet support 5.2.

They have said in esensi/model#25 that they are planning an update soon. Hopefully by this time the hiendv/entrust PR will be merged back in to the main Entrust package.

Sorry for the inconvenience!

**Comment by ruelluna** [comment]
Thanks! Can't wait!

**Comment by acoustep** [comment]
Hi @ruelluna 

Thank you for your patience! I have just finished updating the project to Laravel 5.2. There are a couple of additional steps, all of which are documented on the 5.2 branch

https://github.com/acoustep/entrust-gui/tree/5.2

If you run in to any problems then let me know :smile:

**Comment by acoustep** [comment]
Closing this as we have a 5.2 branch working :)

**Comment by saifkinyori** [comment]
Can it support 5.5?
