### ISSUE TITLE
changing the user's model name

### ISSUE THREAD

**Issue by meyer59** [acoustep/entrust-gui#31]
Hi ,
there is anyways to change the user model referenced by the plugin ?
Let's say that my users table/model name is backend_users
Thank you

**Comment by acoustep** [comment]
Hi @meyer59 

For Laravel 5.2+ this package relies on the following configuration to get your User model

```
Config::get('auth.providers.users.model');
```
If you update the model class there it should use it. 

If you need to, you can set the ```protected $table``` attribute in the class to use a different database table name.

**Comment by meyer59** [comment]
Thanks a lot
