### ISSUE TITLE
Routes add subdomain

### ISSUE THREAD

**Issue by angelkurten** [acoustep/entrust-gui#33]
Publish routes for add domain
Example: http://stackoverflow.com/questions/21326980/how-to-use-the-laravel-subdomain-routing-function

**Comment by acoustep** [comment]
Hi @angelkurten 

What would the use case for this be? This seems a bit out of scope for the package.

**Comment by angelkurten** [comment]
Hi @acoustep 

I have platform in subdomain app.example.com/admin
