### ISSUE TITLE
Problems on changing route-prefix with entrust-gui 5.2

### ISSUE THREAD

**Issue by steve-ks** [acoustep/entrust-gui#34]
Hi there,
just came around this marvelous package for the entrust gui pages. I am using laravel 5.4, entrust 5.2.x-dev and entrust-gui 5.2.x-dev. In a basic test everything worked well, the gui immediately showed me all my pre-configured users, roles and permissions. Without reconfiguring anything, I was able to add and edit users, have not tested roles and permissions but I guess they are fine too. 

Now I've changed the configuration to use following:
```<?php
return [
//    "layout" => "entrust-gui::app",
    "layout" => "layouts.app",
    "route-prefix" => "entrust-gui",
//    "route-prefix" => "config",
    "pagination" => [
        "users" => 10,
        "roles" => 10,
        "permissions" => 10,
    ],
    "middleware" => ['web', 'entrust-gui.admin'],
    "unauthorized-url" => '/login',
    "middleware-role" => 'admin',
    "confirmable" => true,
    "users" => [
      'fieldSearchable' => [],
    ],
];
```

As shown I actually only changed two configurations, that is using my own layout which worked very well, having still all functionality. Now as soon as I change the route-prefix from entrust-gui to config, it seems that everything breaks. When creating users, it will just redirect me to the users/index page without changing any data. When editing users, it redirects me to the config/users/{id} page - which does not exist hence giving me an exception - and does not edit the user data either. 

I tested some configurations through but did not come to any final solution so far. This seems to be related to Issue #29.

Greetings, 
Steve

**Comment by acoustep** [comment]
Sorry for the delayed response.

I have replicated this environment with Laravel 5.4 and switched to the route prefix to `config` and I'm not running into any issues.

If you're still working on this: did you change any of the template files or is there any middleware that could be causing an issue?

**Comment by acoustep** [comment]
Closing this due to no response. Feel free to re-open if you're still having issues and can provide further details.
