### ISSUE TITLE
Where do i place permissions

### ISSUE THREAD

**Issue by rebirthtobi** [acoustep/entrust-gui#35]
a newbie at Laravel and currently working with
entrust-gui . please i will like to know how to attach the permission
to my routes or probably the question is what are the possible places
to put permissions after setting up entrust-gui.

**Comment by acoustep** [comment]
Hi @MrCheckMate, Welcome to the world of Laravel!

Entrust GUI is just a user interface for [Entrust](https://github.com/Zizaco/entrust).

I would recommend reading through the documentation for Entrust to see what you're able to do

**Comment by rebirthtobi** [comment]
Thanks, i figured it out have digging on it, thanks
