### ISSUE TITLE
5.5 Support

### ISSUE THREAD

**Issue by saifkinyori** [acoustep/entrust-gui#37]
Does this package support 5.5?

**Comment by acoustep** [comment]
I haven't tested this with 5.5 yet. I'll be looking at this soon.

**Comment by acoustep** [comment]
The installation _almost_ works. There is an issue to do with Entrust's migration which fails in 5.5

There is a workaround (and hopefully a release soon to come) available here: https://github.com/Zizaco/entrust/pull/840

After that the system installs. There is one issue that I've found so far which I'll be working on  (https://github.com/acoustep/entrust-gui/issues/38). 

 I'll be fixing that and doing further testing before making a release.

**Comment by acoustep** [comment]
Hi @saifkinyori,

I've fixed the one issue that I've found so far and drafted a 0.6.0 release for it. The main issue is with Entrust rather than Entrust GUI. With the above-mentioned workaround, everything should work.

If you find any issues let me know.
