### ISSUE TITLE
Can't install on laravel 5.5 and "zizaco/entrust": "dev-master"

### ISSUE THREAD

**Issue by agamayaservers** [acoustep/entrust-gui#39]
I have installed Entrust as "zizaco/entrust": "dev-master"
After that I can't install Entrust-GUI with this error message of composer update command:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for acoustep/entrust-gui dev-master -> satisfiable by acoustep/entrust-gui[dev-master].
    - acoustep/entrust-gui dev-master requires zizaco/entrust ~1.4.0 -> satisfiable by zizaco/entrust[1.4.0, 1.4.1] but these conflict with your requirements or minimum-stability.

What should I do to install Entrust-GUI correctly ?

**Comment by agamayaservers** [comment]
solved the problem with setting stability flag like this:
"acoustep/entrust-gui": "@dev"

**Comment by acoustep** [comment]
Hi @agamayaservers I'm glad you got it working 🙂

For future reference, and anyone else that has a similar issue, make sure you use the 5.2 branch and follow those instructions for 5.5 compatability.
