### ISSUE TITLE
Laravel 5.2 missing controller and middleware

### ISSUE THREAD

**Issue by cyberfly** [acoustep/entrust-gui#4]
Hi I just tested with latest version of Laravel

It seems there is no controller and middleware needed in my app/HTTP folder

Did I miss any step to generate that controller?

I check your Github code there is some controller that I dont have

Thanks

**Comment by cyberfly** [comment]
Nevermind I found it in vendor directory. However I still facing this error when visiting USERS route

FatalErrorException in AdminAuth.php line 58: Call to undefined method Illuminate\Http\Response::make()

**Comment by acoustep** [comment]
Hi @cyberfly 

Sorry for the delay, I am looking in to this issue when I get chance - however it should be avoidable for now.

That line is for users that are logged in but don't have the role to view Entrust GUI (e.g admin role)

If your user has some kind of admin role already then make sure it is set in the `config/entrust-gui.php` option `middleware-role` (case sensitivity matters as well).

If your user account does not have an admin role, then you can either set it in your database manually or temporarily (in a local dev environment) remove `entrust-gui.admin` middleware in the config. Then create an `admin` role and associate it to your user account from the GUI and put the middleware back on afterwards.

**Comment by cyberfly** [comment]
Thanks problem solved just by add in the 'admin' role
