### ISSUE TITLE
The password confirmation does not match.

### ISSUE THREAD

**Issue by JSetup** [acoustep/entrust-gui#40]
Hello, I have a problem with the password confirmation, I am using laravel 5.3, before I had seen an error from another person who had the same, I did what they recommended, which was to put..

`public function entrustPasswordHash() 
    {
        $this->password = Hash::make($this->password);
        $this->forceSave();
    }`

help me please, I already have days with the same, I've tried in different ways, I've even got to change code from the same entrust: '(

**Comment by JSetup** [comment]
already solved, thank you! :)

**Comment by windchime18** [comment]
may i know  how it was resolved?
