### ISSUE TITLE
errno: 150 "Foreign key constraint is incorrectly formed" [SOLUTION]

### ISSUE THREAD

**Issue by theArgus** [acoustep/entrust-gui#43]
Hi everybody,

After trying to make de migration with the correct rules configuration found the solution to the problem:  
`Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `plataforma_aconsa`.`role_user` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)
`
Here you put that the solution were just remove the lines 
`$table->foreign('user_id')->references('id')->on('users')
                ->onUpdate('cascade')->onDelete('cascade');
            $table->foreign('role_id')->references('id')->on('roles')
                ->onUpdate('cascade')->onDelete('cascade');`
But with that just migrate without the correct rules.
The table users contain the PK like  **bigIncrements** so the problem is the compatibility between users PK and role_user FK declaration.
So, you have to put for FK **bigInteger** and the Scheme must be like this:
`Schema::create('role_user', function (Blueprint $table) {
            $table->bigInteger('user_id')->unsigned();
            $table->integer('role_id')->unsigned();

            $table->foreign('user_id')->references('id')->on('users')
                ->onUpdate('cascade')->onDelete('cascade');
            $table->foreign('role_id')->references('id')->on('roles')
                ->onUpdate('cascade')->onDelete('cascade');

            $table->primary(['user_id', 'role_id']);
        });`
After just migrate:
 describe role_user;
+---------+---------------------+------+-----+---------+-------+
| Field   | Type                | Null | Key | Default | Extra |
+---------+---------------------+------+-----+---------+-------+
| user_id | bigint(20) unsigned | NO   | PRI | NULL    |       |
| role_id | int(10) unsigned    | NO   | PRI | NULL    |       |
+---------+---------------------+------+-----+---------+-------+
Hope it can be help.

**Comment by acoustep** [comment]
Interesting, thanks @theArgus , I'll see if I can add this to the instructions :)

**Comment by theArgus** [comment]
Your welcome, I really loved to help you. This project is too useful.

**Comment by acoustep** [comment]
I've updated the 5.8 instructions to include this. Thanks again @theArgus , I will now close the ticket.
