### ISSUE TITLE
Encrypting the password when changed

### ISSUE THREAD

**Issue by austinkregel** [acoustep/entrust-gui#5]
I was wondering how I could enable the password encryption without having to edit any of your code. I noitced that you're [saving without hashing](https://github.com/acoustep/entrust-gui/blob/master/src/Repositories/UserRepositoryEloquent.php#L83) and that it's not toggleable. Is there anyway it could be a config option or something?

**Comment by acoustep** [comment]
That line should only called when the password isn't entered by the user (see [here](https://github.com/acoustep/entrust-gui/blob/master/src/Repositories/UserRepositoryEloquent.php#L78)). If the user doesn't edit their password, then it should be left unchanged so the hashing isn't called.

The HashingModelTrait on the user model should hash the password if it has been entered, is this not the case?

**Comment by austinkregel** [comment]
Looks like I didn't have the password hash set, but it messes up other packages I have that don't use HashingModelTrait. It also messes up my registration, this is because it's rehashing the already hashed password.

**Comment by acoustep** [comment]
I see, could you tell me which packages you are using which are affected?

I will look at making an option that does not require the HashingModelTrait over the next couple of days.

**Comment by austinkregel** [comment]
Well, it seems any kind of default scaffolding for authentication in Laravel. Laravel Spark (the alpha) is also affected by this. It double hashes the passwords, making them impossible to reset or do really anything with. 

My [Warden package](https://github.com/austinkregel/warden), and my [AuthLogin package](https://github.com/austinkregel/laravel-auth-login) are also affected because they hash the password when creating the model. I have created a "work around" (it's really just a hack) with my Warden package, basically just checking to see if `$hashable` is attached to the model, if it is, it doesn't hash the password.

**Comment by jvalentinei** [comment]
I'm having a similar issue where entrust-gui is using a different method of hashing the password than we use in our AuthController class, where we use bcrypt. When I enable $hashable, the admin gui is able to hash the password, but it's not the same hashing technique. Is there a way to override either how to hash the password or creating the user that will work with entrust-gui?

**Comment by austinkregel** [comment]
From my understanding when you have `$hashable` on your model and the `HashingModelInterface` you don't need to use bcrypt to hash your password, what ends up happening is it hashes the hash of the password you give it. I would say if you can, don't use bcrypt to hash your model.

**Comment by jvalentinei** [comment]
I would prefer to use the encryption method that works best for my purposes, and I think it would make entrust-gui more flexible if the user was able to override the encryption method with their own.

**Comment by austinkregel** [comment]
I agree with you completely, but until this is addressed by acoustep you either have to use another package for user management or you just  have to avoid this package's user management. :/

**Comment by acoustep** [comment]
I've just pushed an update for the 5.2 branch.

I've removed the requirement of `Esensi\Model\Traits\HashingModelTrait` which was doing the automatic hashing and instead required a new method to be implemented in the User model.

This means that
1. The hashing method is only called when inside the Entrust GUI system. Laravel's built in registration, Spark etc should be unaffected now.
2. You can choose which Hashing algorithm you prefer.

I've updated the docs, but here's an example of a User model:

```
<?php namespace App;

use Esensi\Model\Contracts\ValidatingModelInterface;
use Esensi\Model\Traits\ValidatingModelTrait;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Acoustep\EntrustGui\Contracts\HashMethodInterface;
use Hash;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, ValidatingModelInterface, HashMethodInterface
{
  use Authenticatable, CanResetPassword, ValidatingModelTrait, EntrustUserTrait;

    protected $throwValidationExceptions = true;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    protected $hashable = ['password'];

    protected $rulesets = [

        'creating' => [
            'email'      => 'required|email|unique:users',
            'password'   => 'required',
        ],

        'updating' => [
            'email'      => 'required|email|unique:users',
            'password'   => '',
        ],
    ];

    public function entrustPasswordHash() 
    {
        $this->password = Hash::make($this->password);
        $this->save();
    }

}
```

Just make sure to include the new interface `HashMethodInterface` and implement the `entrustPasswordHash` method. Make sure you remove HashingModelInterface and HashingModelTrait as they are what will cause issues with additional hashing.

One thing I'm looking in to currently is validation when Laravel's registration validation fails. I'll have to get back to you guys on that one ASAP.

**Comment by jvalentinei** [comment]
That worked perfectly! Thanks much for the code update and instructions on how to update my code!

**Comment by acoustep** [comment]
Just to add to my previous comment on Laravel registration failing: After further investigation, Laravel's built in authentication validation works fine assuming you have this in your Auth//AuthController

```
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

```

The error I was getting previously was due to the Whoops exception package which when removed works fine.
