### ISSUE TITLE
Publish controller?

### ISSUE THREAD

**Issue by ethanclevenger91** [acoustep/entrust-gui#8]
I need to perform some of my own logic in the user controller - specifically I've added a file field to attach profile pictures to a user. Is there any way to reference an alternate controller, or publish yours?

**Comment by acoustep** [comment]
There's no option to publish the controllers currently.

A quick solution would be to listen for the `UserCreatedEvent` and `UserUpdatedEvent`. Which would let you access the user instance, handle a file upload and save it to the user.

More info here: https://github.com/acoustep/entrust-gui#events

**Comment by ethanclevenger91** [comment]
I can't access the request variable from there, can I?

**Comment by ethanclevenger91** [comment]
Nvm, it's on the container, so yes. Excellent - thanks!
