### ISSUE TITLE
Migrate old entrust(without GUI) to new entrust(With GUI) 

### ISSUE THREAD

**Issue by san3jaya** [acoustep/entrust-gui#9]
I am developing a CMS with entrust. And I used entrust package witch not include GUI. So how I remove that entrust and replace this package.

**Comment by acoustep** [comment]
This package should work fine if you're already using Entrust.

Assuming you're on Laravel 5.2, In your `composer.json` you should remove your current version of Entrust and replace it with

```
"acoustep/entrust-gui": "5.2.x-dev",
"zizaco/entrust": "5.2.x-dev"
```

Run `composer update` and follow the rest of the installation instructions. You probably already have migration files set up so you don't have to run `php artisan entrust:migration` or `php artisan migrate again`.
